import Head from 'next/head'
import { useEffect, useState } from 'react'
import dynamic from 'next/dynamic';


import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Card, Text, Button, Row } from "@nextui-org/react";
import Presscard from '@/Components/Presscard'

const inter = Inter({ subsets: ['latin'] })

export default function Home({quotes}) {

  const[quote, setQuote] = useState(quotes)

  // useEffect(() => {
  //   fetch("https://animechan.vercel.app/api/random")
  //   .then((response) => response.json())
  //   .then((q) => {
  //     console.log(q)
  //     // console.log("asd")
  //     setQuote(q)
  //   });
  
    
  // }, [])
  
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={styles.main}>
        
      </main> */}
      <div className={styles.main}>
      <div className={styles.quote}>


       <Card variant="bordered" className={styles.card}>
        <div className={styles.blur}>
          {/* <img src="quote_background.webp" /> */}
          <Card.Header >
            <Text  size={25} color=" #f0d5f6 ">{quote.anime} </Text>
          </Card.Header>
          <Card.Divider css={{border:"1px groove whitesmoke"}}/>
          <Card.Body css={{ py: "$10"}} >
            
            <Text b size={20} color=" #7bf1e9 " >
             {quote.quote}
            </Text>
           
    <Row justify="flex-end">
              <Text b size={17} color=" #fc3291">--- {quote.character} </Text>
              
            </Row>
          </Card.Body>
          
          <Card.Footer>
            
          </Card.Footer>
          </div>
        </Card>
      </div>
      
      <div className={styles.presscards}>
        <div className={styles.blur2}>
      <Presscard src="press_anime_2.webp" content="Anime Recommendations" link="Anime"/>
      <Presscard src="press_movies.jpeg" content="Movies Recommendations" link="Movies"/>
      <Presscard src="press_series.jpg" content="Series Recommendations" link="Tvseries"/>
      </div>
      </div>
      </div>
    </>
  )
}

export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch('https://animechan.vercel.app/api/random')
  const quotes = await res.json()

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      quotes,
    },
  }
}
